# Generated by Django 2.1.4 on 2019-01-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_contact_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reciepts',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
