# Generated by Django 2.1.4 on 2019-01-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_payment_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='photo_1',
            new_name='item_1',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_2',
            new_name='item_2',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_3',
            new_name='item_3',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_4',
            new_name='item_4',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_5',
            new_name='item_5',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_6',
            new_name='item_6',
        ),
    ]
