# Generated by Django 2.1.4 on 2019-01-04 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20190104_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='item_1',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='item_2',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='item_3',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='item_4',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='item_5',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='item_6',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_main',
        ),
    ]
