# Generated by Django 2.1.4 on 2019-01-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20190106_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='photo_1',
            new_name='item_1',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_2',
            new_name='item_2',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_3',
            new_name='item_3',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_4',
            new_name='item_4',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_5',
            new_name='item_5',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_6',
            new_name='item_6',
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
