# Generated by Django 2.1.4 on 2019-01-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20190106_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='city',
            new_name='location',
        ),
    ]
