# Generated by Django 2.1.4 on 2019-01-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='plot_location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
