# Generated by Django 2.1.4 on 2019-01-04 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_plot_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='amounttobepaid_monthly',
            new_name='monthly_payment',
        ),
        migrations.AddField(
            model_name='accounts',
            name='total_amount_paid',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
