# Generated by Django 2.1.4 on 2019-01-04 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190104_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='Balance',
            new_name='balance',
        ),
    ]
