# Generated by Django 2.1.4 on 2019-01-04 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190104_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='monthly_payment',
        ),
    ]
