# Generated by Django 2.1.4 on 2019-01-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_accounts_agreed_payment_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='total_amount_paid',
            new_name='total_paid_amount',
        ),
    ]
