# Generated by Django 2.1.4 on 2019-01-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190104_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='total_paid_amount',
            new_name='amount_paid',
        ),
    ]
