# Generated by Django 2.1.4 on 2019-01-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190104_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='totalamountpaid',
        ),
        migrations.AddField(
            model_name='accounts',
            name='amountpaidtotal',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
