# Generated by Django 2.1.4 on 2019-01-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190104_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='amountpaidtotal',
            new_name='paid',
        ),
    ]
