# Generated by Django 2.1.4 on 2019-01-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190104_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='total_paid',
        ),
    ]
