# Generated by Django 2.1.4 on 2019-01-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190104_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='payment_schedule',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='plot_location',
        ),
        migrations.AddField(
            model_name='accounts',
            name='Balance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='accounts',
            name='deposit',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='accounts',
            name='monthlypay',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='accounts',
            name='paid',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
