# Generated by Django 2.1.4 on 2019-01-04 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20190104_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='listing_id',
            new_name='buying_price',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='photo_1',
            new_name='item_1',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='photo_2',
            new_name='item_2',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='photo_3',
            new_name='item_3',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='photo_4',
            new_name='item_4',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='photo_5',
            new_name='item_5',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='photo_6',
            new_name='item_6',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='user_id',
            new_name='sqft',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='Balance',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='email',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='monthlypay',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='name',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='personalidnumber',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='photo_personal',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='plot_Buying_price',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='plot_number',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='plot_size',
        ),
        migrations.AddField(
            model_name='accounts',
            name='address',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='accounts',
            name='city',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='accounts',
            name='electricity',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='accounts',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='accounts',
            name='lot_size',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='accounts',
            name='payment_deposit',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='accounts',
            name='payment_due',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='accounts',
            name='payment_made',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='accounts',
            name='plot_type',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='accounts',
            name='roads',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='accounts',
            name='state',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='accounts',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='accounts',
            name='water',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='accounts',
            name='zipcode',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='description',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='message',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='payment_plan',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
