# Generated by Django 2.1.4 on 2019-01-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20190104_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='realtor',
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
