# Generated by Django 2.1.4 on 2019-01-04 12:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
        ('accounts', '0018_auto_20190104_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200)),
                ('address', models.CharField(default=None, max_length=200)),
                ('city', models.CharField(default=None, max_length=100)),
                ('state', models.CharField(default=None, max_length=100)),
                ('zipcode', models.CharField(default=None, max_length=20)),
                ('buying_price', models.IntegerField()),
                ('payment_plan', models.CharField(default=None, max_length=200)),
                ('payment_deposit', models.CharField(default=None, max_length=200)),
                ('payment_made', models.CharField(default=None, max_length=200)),
                ('payment_due', models.CharField(default=None, max_length=200)),
                ('water', models.CharField(default=None, max_length=100)),
                ('roads', models.CharField(default=None, max_length=100)),
                ('electricity', models.CharField(default=None, max_length=100)),
                ('plot_type', models.CharField(default=None, max_length=100)),
                ('lot_size', models.CharField(default=None, max_length=100)),
                ('sqft', models.IntegerField()),
                ('description', models.TextField(blank=True, default=None)),
                ('message', models.TextField(blank=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('item_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('item_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('item_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('item_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('item_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('item_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.Realtor')),
            ],
        ),
    ]
