# Generated by Django 2.1.4 on 2019-01-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='accounts',
            name='listing',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='accounts',
            name='listing_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='accounts',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='buying_price',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='item_1',
            field=models.ImageField(blank=True, default=None, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='item_2',
            field=models.ImageField(blank=True, default=None, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='item_3',
            field=models.ImageField(blank=True, default=None, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='item_4',
            field=models.ImageField(blank=True, default=None, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='item_5',
            field=models.ImageField(blank=True, default=None, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='item_6',
            field=models.ImageField(blank=True, default=None, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='message',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='photo_main',
            field=models.ImageField(default=None, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='sqft',
            field=models.IntegerField(default=None),
        ),
    ]
