# Generated by Django 2.1.4 on 2019-01-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20190104_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='address',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='city',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='electricity',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='roads',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='state',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='title',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='water',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='zipcode',
        ),
    ]
