# Generated by Django 2.1.4 on 2019-01-04 15:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
        ('accounts', '0021_auto_20190104_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.CharField(default=None, max_length=200)),
                ('listing_id', models.IntegerField(default=None)),
                ('buying_price', models.IntegerField(default=None)),
                ('location', models.CharField(default=None, max_length=200)),
                ('name', models.CharField(default=None, max_length=200)),
                ('email', models.CharField(default=None, max_length=100)),
                ('payment_plan', models.CharField(default=None, max_length=200)),
                ('payment_deposit', models.CharField(default=None, max_length=200)),
                ('payment_made', models.CharField(default=None, max_length=200)),
                ('payment_due', models.CharField(default=None, max_length=200)),
                ('plot_type', models.CharField(default=None, max_length=100)),
                ('lot_size', models.CharField(default=None, max_length=100)),
                ('sqft', models.IntegerField(default=None)),
                ('description', models.TextField(blank=True, default=None)),
                ('message', models.TextField(blank=True, default=None)),
                ('item_main', models.ImageField(default=None, upload_to='photos/%Y/%m/%d/')),
                ('item_1', models.ImageField(blank=True, default=None, upload_to='photos/%Y/%m/%d/')),
                ('item_2', models.ImageField(blank=True, default=None, upload_to='photos/%Y/%m/%d/')),
                ('item_3', models.ImageField(blank=True, default=None, upload_to='photos/%Y/%m/%d/')),
                ('item_4', models.ImageField(blank=True, default=None, upload_to='photos/%Y/%m/%d/')),
                ('item_5', models.ImageField(blank=True, default=None, upload_to='photos/%Y/%m/%d/')),
                ('item_6', models.ImageField(blank=True, default=None, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.Realtor')),
            ],
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='realtor',
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
