# Generated by Django 2.1.4 on 2019-01-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20190104_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
