# Generated by Django 2.1.4 on 2019-01-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20190104_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='item_1',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='item_2',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='item_3',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='item_4',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='item_5',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='item_6',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='item_main',
        ),
    ]
