# Generated by Django 2.1.4 on 2019-01-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20190106_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='message',
        ),
    ]
