lot_size_choices = {
  '40X80ft Approx':'40X80ft Approx',
  '50X100ft Approx':'50X100ft Approx',
  '100X100ft Approx':'100X100ft Approx',
  '1 Acre':'1 Acre',
  '2 Acre':'2 Acre',
  '3 Acre':'3 Acre',
  '4 Acre':'4 Acre',
  '5 Acre':'5 Acre',
  '6 Acre':'6 Acre',
  '7 Acre':'7 Acre',
  '8 Acre':'8 Acre',
  '9 Acre':'9 Acre',
  '10 Acre':'10 Acre',
  '100+ Acre':'100+ Acre',


  
  }

price_choices = {
  '100000':'Kes100,000',
  '200000':'Kes200,000',
  '300000':'Kes300,000',
  '400000':'Kes400,000',
  '500000':'Kes500,000',
  '600000':'Kes600,000',
  '700000':'Kes700,000',
  '800000':'Kes800,000',
  '900000':'Kes900,000',
  '1000000':'Kes1M+',
  '10000000':'Kes10M+',
}

state_choices = {
        'Baringo': 'Baringo',
        'Bomet': 'Bomet',
        'Bungoma': 'Bungoma',
        'Busia': 'Busia',
        'Elgeyo-Marakwet': 'Elgeyo-Marakwet',
        'Embu': 'Embu',
        'Homa Bay': 'Homa Bay',
        'Garissa': 'Garissa',
        'Isiolo': 'Isiolo',
        'Kajiado': 'Kajiado',
        'Kakamega': 'Kakamega',
        'Kericho': 'Kericho',
        'Kiambu': 'Kiambu',
        'Kilifi': 'Kilifi',
        'Kirinyaga': 'Kirinyaga',
        'Kisii': 'Kisii',
        'Kisumu': 'Kisumu',
        'Kitui': 'Kitui',
        'Laikipia': 'Laikipia',
        'Lamu': 'Lamu',
        'Machakos': 'Machakos',
        'Mandera': 'Mandera',
        'Makueni': 'Makueni',
        'Meru': 'Meru',
        'Migori': 'Migori',
        'Mombasa': 'Mombasa',
        'Muranga': 'Muranga',
        'Nairobi': 'Nairobi',
        'Nakuru': 'Nakuru',
        'Narok': 'Narok',
        'Nandi': 'Nandi',
        'Nyamira': 'Nyamira',
        'Nyandarua': 'Nyandarua',
        'Nyeri': 'Nyeri',
        'Samburu': 'Samburu',
        'Siaya': 'Siaya',
        'Taita-Taveta': 'Taita-Taveta',
        'Tana River': 'Tana River',
        'Trans Nzoia': 'Trans Nzoia',
        'Turkana': 'Turkana',
        'Tharaka-Nithi': 'Tharaka-Nithi',
        'Uasin Gishu': 'Uasin Gishu',
        'Vihiga': 'Vihiga',
        'Wajir': 'Wajir',
}